#!/usr/bin/perl

# Boris Uzhinskiy, Insitu LLC 2017

use IO::Handle;STDOUT->autoflush(1);

my $dur = 0 + int(rand(1000));
my $r = $dur % 3;
sleep(12);
if ($r eq 0) {
    exit 0;
} elsif ($r eq 1) { 
    exit 1;
} 